# fly.toml app configuration file generated for public-falling-sun-214 on 2024-11-24T18:53:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kuhree-wiki'
primary_region = 'iad'

[env]
PORT=8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
